### ISSUE TITLE
Using preserveAspectRatio

### ISSUE THREAD

**Issue by roblevintennis** [oreillymedia/svg-essentials-examples#1]
Since it's such an abstract concept, the figure 3.5 examples from the book would be extremely helpful to have up here; especially if you include the `contenteditable` tool like how you have on the other pages. This was actually the point in my reading where I first decided to visit this github.io site since all the concepts up to this one were easy enough to just read about or pound in to vim and open in local browser. Since it's in the index as unlinked I presume there are plans to add but thought I'd open an issue with some real reader (me) feedback on how helpful this would be to get included :+1:

**Comment by AmeliaBR** [comment]
Thanks for the feedback, Rob. (And sorry it took 2 1/2 weeks for a reply!  I need to change my notification settings, clearly.)

I think the example you were looking for is at
http://oreillymedia.github.io/svg-essentials-examples/ch03/meet_slice_specifier.html

Sorry about the dead link in the index -- that was a simple markdown syntax error on my part!  (Fixed now)

If you're curious about any of the other non-interactive SVG figures, you can find files in the "static_figures" directory.  E.g., the basic SVGs for the chapter 3 figures are here:
https://github.com/oreillymedia/svg-essentials-examples/tree/gh-pages/static_figures/ch03

Hope you've been enjoying the book as a whole.  Let us know if you find any other bugs, in the examples or while trying to find them!

~ABR

**Comment by roblevintennis** [comment]
@AmeliaBR Thanks for getting back. Yes I've been enjoying it and about half through. I'll likely skip some chapters for the time being like filters, etc., since I'm not doing that yet. So far seems that it'll be a great reference and the github.io examples are just a great resource and doubles the value of the book

I've posted a couple of issues on the orielly errata site otherwise but nothing too major or blocking yet
