### ISSUE TITLE
confusion over preferred use of ecmascript MIME type

### ISSUE THREAD

**Issue by roblevintennis** [oreillymedia/svg-essentials-examples#2]
@AmeliaBR getting further in the book and it's been amazingly well done (even grammatically which is rare for tech books!) kudos

Not an issue per se, but after having read most of the book and the section scripting svg p.213 onwards, I found myself wondering exactly why `application/ecmascript` is preferred for scripting over js mime type. I ignored my confusion until this morning, I again, ran in to an article which just essentially says it's the default mime type for svg (I had to find [spec](http://www.w3.org/TR/SVG/script.html#DefaultScriptingLanguage) to understand what he meant):
http://bigbitecreative.com/introduction-svg-animation/  (see the section towards bottom "The click event problem"). I know ecmascript is a super-set but I wonder if there are any limitations of what's available to me when coding in such environment ex. avoid such and such.

I think your errata or this github.io site would be an great place to explain in more detail such an "appendix'y" thing and maybe even show an example of change the mime type via `contentScriptType='application/javascript` for example. Thoughts?

**Comment by AmeliaBR** [comment]
This is really a historical debate that goes far beyond the scope of SVG.  Here are a couple quick clarifications:
- ECMAScript isn't a "super-set" of JavaScript, it _is_ (the standardized form of) JavaScript.  Prior to standardization, different browsers had their own implementations which weren't always consistent with each other.
- The official MIME type for ECMAScript is `application/ecmascript`.  This recognizes the fact that it is an executable file (application) not a written document.   _However,_ the `text/javascript` type was already commonly used by the time ECMAScript was standardized, so for backwards compatibility reasons many programmers continued to use it for their HTML `<script>` elements and for the file headers sent by their servers.  It is now accepted as the official default value for scripts in HTML 5.  However, the SVG spec was written at a time when XML and standardization was expected to wash clean all the messy quirks from pre-standards HTML, so it used the media type identifier that was recommended at the time.
- Most browsers will treat `application/ecmascript`, `application/javascript`, and `text/javascript` as synonyms.  However, some other SVG tools, such as those based on the Batik Java code,[1] might choke on anything other than the ECMAScript version.
- To save headaches, you can just ignore the MIME type and let the defaults work.  The browser will parse the default `text/javascript` for code you write in an HTML script element in exactly the same way as the default `application/ecmascript` for code you write in an SVG script element.  

---

1: Side note.  Although scripts have a default type in the SVG specs, style blocks don't.  All browsers assume that a style block will be CSS if you don't specify a type, but Batik will ignore your styles unless you  use `<style type="text/css">`.

**Comment by roblevintennis** [comment]
@AmeliaBR wow, those are just great clarifications. Thanks
